// Write the home-screen install block into the single-player index.html.
//
// This is the ROOT build only. The online build under multiplayer/ has a real
// manifest.webmanifest, real PNG icons and a service worker instead — it is
// served from its own origin by the relay, so it can have files beside it, and
// a service worker (which can never be inlined) is what earns a proper
// install. This inline version exists because the root page ships as one file.
//
// Installing the page on an Android home screen and losing the address bar is
// one thing: a web app manifest saying `display: standalone`. The manifest here
// is a data: URL in the page rather than a manifest.json beside it, because
// this build ships as one self-contained file — a lone copy of index.html still
// installs, wherever it is served from. The cost is that start_url and scope
// cannot be used (a relative URL has nothing to resolve against in a data:
// manifest) and there is no service worker, so no install prompt and no
// offline start. multiplayer/ pays files for those instead.
//
// The encoding is not something to hand-edit. The icon is a data: URL nested
// inside a data: URL, so its own %XX escapes are written twice to survive the
// browser's single decode of the outer one; and an apostrophe left raw would
// close the single-quoted href and truncate the manifest mid-string. Edit the
// values below and re-run instead:
//
//   node tools/manifest.mjs           # rewrite the block in index.html
//   node tools/manifest.mjs --print   # print the block, change nothing
//
// Chrome takes an SVG icon with "sizes":"any" as installable, which is why
// there is no PNG here to keep in sync with the game's colours.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PAGES = ['index.html'];

// The block is fenced by these markers so this tool can find and replace it
// exactly, without a regex having to understand the encoded soup between them.
const BEGIN = '<!-- BEGIN home-screen install block — generated by tools/manifest.mjs -->';
const END = '<!-- END home-screen install block -->';

const BG = '#0c0b10';      // the page background, so the splash matches the game
const TITLE = 'Barrage';

// A shell already in the air, in the game's own ground and accent colours.
const ICON_SVG =
  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128">' +
  `<rect width="128" height="128" fill="${BG}"/>` +
  '<rect y="104" width="128" height="24" fill="#4a3728"/>' +
  '<path d="M74 78 L112 48 L119 57 L81 87 Z" fill="#ff7a45"/>' +
  '<rect x="20" y="76" width="60" height="22" rx="8" fill="#ff7a45"/>' +
  '<circle cx="104" cy="30" r="7" fill="#ece7e1"/></svg>';

// encodeURIComponent leaves ' ( ) ! * ~ alone; the apostrophe is the one that
// matters here, since these strings end up inside single-quoted attributes.
const enc = (s) => encodeURIComponent(s).replace(/'/g, '%27');

const ICON = 'data:image/svg+xml,' + enc(ICON_SVG);

// No start_url: a relative one cannot resolve against a data: manifest, and
// with it absent the app starts at the page it was installed from.
const MANIFEST = {
  name: 'Barrage — Tank Artillery',
  short_name: TITLE,
  display: 'standalone',
  orientation: 'landscape',
  background_color: BG,
  theme_color: BG,
  icons: [{ src: ICON, sizes: 'any', type: 'image/svg+xml', purpose: 'any maskable' }],
};

const HREF = 'data:application/manifest+json,' + enc(JSON.stringify(MANIFEST));

const BLOCK = [
  BEGIN,
  `<link rel="manifest" href='${HREF}'>`,
  '<!-- display:standalone in the manifest is what drops the address bar on',
  '     Android; these are the older switches Chrome and iOS Safari read for',
  '     the same thing, and they still work where the manifest is ignored. -->',
  '<meta name="mobile-web-app-capable" content="yes">',
  '<meta name="apple-mobile-web-app-capable" content="yes">',
  '<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">',
  `<meta name="apple-mobile-web-app-title" content="${TITLE}">`,
  `<meta name="application-name" content="${TITLE}">`,
  `<meta name="theme-color" content="${BG}">`,
  `<link rel="icon" href='${ICON}' type="image/svg+xml">`,
  `<link rel="apple-touch-icon" href='${ICON}'>`,
  END,
].join('\n');

if (process.argv.includes('--print')) {
  console.log(BLOCK);
  process.exit(0);
}

// The block goes right after <title>, and replaces itself on a re-run.
const ANCHOR = '<title>Barrage — Tank Artillery</title>\n';

for (const page of PAGES) {
  const file = join(ROOT, page);
  const html = readFileSync(file, 'utf8');
  let next;
  if (html.includes(BEGIN)) {
    const from = html.indexOf(BEGIN);
    const to = html.indexOf(END, from);
    if (to < 0) throw new Error(`${page}: install block has a start but no end`);
    next = html.slice(0, from) + BLOCK + html.slice(to + END.length);
  } else {
    if (!html.includes(ANCHOR)) throw new Error(`${page}: <title> anchor not found`);
    next = html.replace(ANCHOR, ANCHOR + BLOCK + '\n');
  }
  if (next === html) { console.log('unchanged:', page); continue; }
  writeFileSync(file, next);
  console.log('wrote:', page);
}
